package br.com.dextra.treinamento.model.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;

/**
 * This class was generated by Apache CXF 2.2.3
 * Sat Mar 19 16:28:58 BRT 2016
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://service.model.treinamento.dextra.com.br", name = "TesteWebServiceImpl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface TesteWebServiceImpl {

    @WebMethod
    public void servicoInvocado();

    @WebMethod
    public void adicionarPost(
        @WebParam(partName = "titulo", name = "titulo")
        java.lang.String titulo,
        @WebParam(partName = "descricao", name = "descricao")
        java.lang.String descricao
    );

    @WebMethod
    public void listarPosts();
}
