
/*
 * 
 */

package br.com.dextra.treinamento.model.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Sat Mar 19 16:28:58 BRT 2016
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "TesteWebServiceImplService", 
                  wsdlLocation = "http://localhost:8080/blog-ejb-1.0-SNAPSHOT/TesteWebServiceImplService/TesteWebServiceImpl?wsdl",
                  targetNamespace = "http://service.model.treinamento.dextra.com.br") 
public class TesteWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.model.treinamento.dextra.com.br", "TesteWebServiceImplService");
    public final static QName TesteWebServiceImplPort = new QName("http://service.model.treinamento.dextra.com.br", "TesteWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/blog-ejb-1.0-SNAPSHOT/TesteWebServiceImplService/TesteWebServiceImpl?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/blog-ejb-1.0-SNAPSHOT/TesteWebServiceImplService/TesteWebServiceImpl?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TesteWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TesteWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TesteWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TesteWebServiceImpl
     */
    @WebEndpoint(name = "TesteWebServiceImplPort")
    public TesteWebServiceImpl getTesteWebServiceImplPort() {
        return super.getPort(TesteWebServiceImplPort, TesteWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TesteWebServiceImpl
     */
    @WebEndpoint(name = "TesteWebServiceImplPort")
    public TesteWebServiceImpl getTesteWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(TesteWebServiceImplPort, TesteWebServiceImpl.class, features);
    }

}
